name: ecom
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0
#----------PACKAGES-----------------#
dependencies:
  flutter:
    sdk: flutter

  #------------UTILITY PACKAGES-----------#
  http: ^1.3.0
  intl: ^0.20.2
  logger: ^2.5.0
  url_launcher: ^6.3.1
  flutter_native_splash: ^2.4.5
  smooth_page_indicator: ^1.2.1
  lottie: ^3.3.1
  connectivity_plus: ^6.1.3

  #-----------ICONS----------------------#
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8

  #------------STATE MANAGEMENT-----------#
  get: ^4.7.2
  get_storage: ^2.1.1
  

  #-----------PRODUCT SPECIFIC-------------#
  readmore: ^3.0.0
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1

  #-----------FireBase------------#
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  google_sign_in: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:


  uses-material-design: true

  # Images
  assets:
    - assets/images/onboarding_images/
    - assets/icons/
    - assets/logos/
    - assets/images/product_images/
    - assets/animation/

  # Fonts
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
