// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_-Ef1c2uaJzg2u5fTq62j3kbliZ86HRE',
    appId: '1:641966995573:android:99dd7e9c900580188fe03c',
    messagingSenderId: '641966995573',
    projectId: 'ecomnepal-24e39',
    storageBucket: 'ecomnepal-24e39.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhB6UGg4jkVT6Gb3ezXYxI7zd7y0auH0k',
    appId: '1:641966995573:ios:8a0568a813fec6418fe03c',
    messagingSenderId: '641966995573',
    projectId: 'ecomnepal-24e39',
    storageBucket: 'ecomnepal-24e39.firebasestorage.app',
    androidClientId: '641966995573-epkb0ubtnllrcs7d4la23o176j60jqru.apps.googleusercontent.com',
    iosClientId: '641966995573-t8quou9915n0m165iaib0q4p4ctfjlco.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecom',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmkdrs_kxRxRytxZOkw9tElNubdbDH7Qc',
    appId: '1:641966995573:web:1f546d955d1360758fe03c',
    messagingSenderId: '641966995573',
    projectId: 'ecomnepal-24e39',
    authDomain: 'ecomnepal-24e39.firebaseapp.com',
    storageBucket: 'ecomnepal-24e39.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhB6UGg4jkVT6Gb3ezXYxI7zd7y0auH0k',
    appId: '1:641966995573:ios:8a0568a813fec6418fe03c',
    messagingSenderId: '641966995573',
    projectId: 'ecomnepal-24e39',
    storageBucket: 'ecomnepal-24e39.firebasestorage.app',
    androidClientId: '641966995573-epkb0ubtnllrcs7d4la23o176j60jqru.apps.googleusercontent.com',
    iosClientId: '641966995573-t8quou9915n0m165iaib0q4p4ctfjlco.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmkdrs_kxRxRytxZOkw9tElNubdbDH7Qc',
    appId: '1:641966995573:web:1e370fb374c54c858fe03c',
    messagingSenderId: '641966995573',
    projectId: 'ecomnepal-24e39',
    authDomain: 'ecomnepal-24e39.firebaseapp.com',
    storageBucket: 'ecomnepal-24e39.firebasestorage.app',
  );

}